// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sargis Khachatryan
#pragma once

#include <QObject>
#include <QGenericPlugin>

namespace liberaqt {

// Entry point. Qt instantiates this during QGuiApplication construction for every plugin named in
// QT_QPA_GENERIC_PLUGINS. We return nullptr from create() -- this is a pure side-effect plugin --
// and defer real work to a zero-delay timer so the event loop is running before we bind a socket.
//
// The metadata carries a key unique to this build's ABI, because an application tree is not one
// ABI: Libero SoC is 32-bit and spawns a 64-bit SmartTime, and every Qt child inherits the
// injection environment. Qt binds a plugin key to exactly one library -- qLoadPlugin takes the
// first match on QT_PLUGIN_PATH and never tries a second -- so when every build claimed only
// "liberaqt", the first directory on the path owned the key and every other architecture was
// locked out in silence. Measured: with the 64-bit directory placed first, 32-bit Libero could no
// longer load its own agent at all.
//
// Pointer size alone does not identify an ABI, which cost a second round of the same bug: a
// 64-bit MinGW build and a 64-bit MSVC build both claimed "liberaqt_64", and installing the
// former stopped SmartTime -- an MSVC application -- from finding the latter. The key is
// generated by CMake from Qt version, pointer size and compiler together (liberaqt_5_15_64_msvc),
// which is the smallest thing that actually distinguishes two loadable plugins.
//
// Each process asks for every installed key and loads the one it can; the rest are refused
// harmlessly, and arming twice is safe because Agent::start() guards on m_started.
class AgentPlugin : public QGenericPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QGenericPluginFactoryInterface_iid FILE "liberaqt_plugin.json")

public:
    explicit AgentPlugin(QObject *parent = nullptr);
    QObject *create(const QString &name, const QString &spec) override;
};

} // namespace liberaqt
